
services:
    mcp_server_app:
        build:
          context: .
          dockerfile: Dockerfile
        image: khulesa/mcp-server:0.3.2
        container_name: mcp_server_app
        ports:
          - "8090:8090"
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-mcp:5432/mydatabase
          - SPRING_DATASOURCE_USERNAME=myuser
          - SPRING_DATASOURCE_PASSWORD=Auto@123
          - SPRING_LIQUIBASE_ENABLED=true
        networks:
          - mcpai

networks:
  mcpai:
    external: true