apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mcp-configmap.yaml
  # - postgres-secret.yaml
  # - postgres-pvc.yaml
  # - postgres-deployment.yaml
  # - postgres-service.yaml
  - ollama-pvc.yaml
  - ollama-deployment.yaml
  - ollama-service.yaml
  - mcp-server-deployment.yaml
  - mcp-server-service.yaml
  - mcp-client-deployment.yaml
  - mcp-client-service.yaml