apiVersion: v1
kind: Service
metadata:
  name: mcp-client-service
spec:
  # LoadBalancer is good for cloud environments. For production, you might use an Ingress.
  type: LoadBalancer
  selector:
    app: mcp-client
  ports:
    - port: 8040
      targetPort: 8040